<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Añadir usuario - Mi base de datos</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href='../css/style.css'>
    <script src="https://kit.fontawesome.com/aaeebdae3e.js" crossorigin="anonymous"></script>
</head>
<body>
    <?php
        session_start();
        include "../scripts/php/funciones.php";

        $inputsRequired = ["dni","nombre","apellido","email","telefono"];
        $errores = [];
        foreach($inputsRequired as $label) {    
            $errores[$label] = "";
            if(empty($_POST[$label]) && isset($_POST[$label])) {
                $errores[$label] = "Este campo es obligatorio";
                $noInsertar = true;
            }
        }
    
    ?>
    <header>
        <h1>Mi base de datos</h1>
        <nav>
            <ul>
                <li><a href="añadir-usuario.phtml" class="active websites"><i class="fa-solid fa-user-plus"></i>Añadir</a></li>
                <li><a href="usuarios_view.html" class="websites"><i class="fa-solid fa-search"></i>Buscar</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <table  class="display" id="myTable">
            <thead>
                <tr>
                    <th>DNI/CIF</th>
                    <th>Nombre</th>
                    <th>Primer apellido</th>
                    <th>Correo electrónico</th>
                    <th>Teléfono</th>
                    <th>Insertar</th>
                </tr>
            </thead>
            <tbody>
                <form action="#" method="post">
                    <tr>
                        <td>
                            <?php echo $errores["dni"]?>
                            <input type="text" maxlength="9" minlength="9" name="dni" value="<?php echo $_GET["dni"]??""?>">
                        </td>
                        <td>
                            <?php echo $errores["nombre"]?>
                            <input type="text" maxlength="45" name="nombre" value="">
                        </td>
                        <td>
                            <?php echo $errores["apellido"]?>
                            <input type="text" maxlength="45" name="apellido" value="">
                        </td>
                        <td>
                            <?php echo $errores["email"]?>
                            <input type="text" maxlength="45" name="email" value="">
                        </td>
                        <td>
                            <?php echo $errores["telefono"]?>
                            <input type="tel" name="telefono" maxlength="15" value="">
                        </td>
                        <td><button type="submit" name="insert" class="actionButton"><i class="fa-solid fa-arrow-right-to-bracket actions"></i></td>
                    </tr>
                </form>
            </tbody>
        </table>
        <?php
        if (isset($_POST["insert"])) {
            $DBFunctions = new Administrador();

            if (!isset($noInsertar)) {
                if ($DBFunctions->checkUsuario($_POST["dni"]) == null) {  
                    $DBFunctions->añadirUsuario($_POST["dni"],$_POST["nombre"],$_POST["apellido"],$_POST["email"],$_POST["telefono"]);
                } else {
                    $DBFunctions->editarUsuario($_POST["dni"],$_POST["nombre"],$_POST["apellido"],$_POST["email"],$_POST["telefono"]);
                }
            }
        }
        ?>
    </main>
    <footer></footer>
</body>
</html>